### ISSUE TITLE
Manual (re)connect not possible

### ISSUE THREAD

**Issue by lgrahl** [threema-ch/threema-web#297]
1. Use the web client and the app until the phenomenon occurs that reconnecting doesn't work, not even when manually pressing on *start session*. This is the hardest step as it's not deterministic. :wink: 
2. Start a different session (that's already trusted) to another browser.
3. The app crashes.
4. Restart the app.
5. The web client works again.

## Log Output

This is all that happens in case I try to restart the session to the browser who currently is unable to connect to the app (step 1):

> 08-11 23:29:30.298 28204 28204 W InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.

And this is what happens once I start a different session (that's already trusted) to another browser:

> 08-11 23:29:35.282 28204 28204 W System.err: abx$a: Error: Called setDisconnecting in state CONNECTING
08-11 23:29:35.315 28204 28204 W System.err: 	at abx.a(SourceFile:51)
08-11 23:29:35.315 28204 28204 W System.err: 	at ace.a(SourceFile:90)
08-11 23:29:35.315 28204 28204 W System.err: 	at aao.a(SourceFile:527)
08-11 23:29:35.315 28204 28204 W System.err: 	at ch.threema.app.webclient.activities.SessionsActivity.a(SourceFile:3488)
08-11 23:29:35.315 28204 28204 W System.err: 	at ch.threema.app.dialogs.SelectorDialog$1.onClick(SourceFile:126)
08-11 23:29:35.315 28204 28204 W System.err: 	at android.support.v7.app.AlertController$AlertParams$3.onItemClick(SourceFile:1046)
08-11 23:29:35.315 28204 28204 W System.err: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
08-11 23:29:35.315 28204 28204 W System.err: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
08-11 23:29:35.315 28204 28204 W System.err: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
08-11 23:29:35.315 28204 28204 W System.err: 	at android.widget.AbsListView$3.run(AbsListView.java:4054)
08-11 23:29:35.315 28204 28204 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
08-11 23:29:35.315 28204 28204 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-11 23:29:35.316 28204 28204 W System.err: 	at android.os.Looper.loop(Looper.java:154)
08-11 23:29:35.316 28204 28204 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-11 23:29:35.316 28204 28204 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 23:29:35.316 28204 28204 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-11 23:29:35.316 28204 28204 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
08-11 23:29:35.316 28204 28204 E Threema : abx$a: Error: Called setDisconnecting in state CONNECTING
08-11 23:29:35.330 28204 28204 E AndroidRuntime: FATAL EXCEPTION: main
08-11 23:29:35.330 28204 28204 E AndroidRuntime: Process: ch.threema.app, PID: 28204
08-11 23:29:35.330 28204 28204 E AndroidRuntime: abx$a: Error: Called setDisconnecting in state CONNECTING
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at abx.a(SourceFile:51)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at ace.a(SourceFile:90)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at aao.a(SourceFile:527)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at ch.threema.app.webclient.activities.SessionsActivity.a(SourceFile:3488)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at ch.threema.app.dialogs.SelectorDialog$1.onClick(SourceFile:126)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.support.v7.app.AlertController$AlertParams$3.onItemClick(SourceFile:1046)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3139)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.widget.AbsListView$3.run(AbsListView.java:4054)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:751)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-11 23:29:35.330 28204 28204 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

## Your Environment
* Threema Web version: 1.4.1
* Threema for Android version: 3.19.2000361
* Threema for Android source: Play Store

This is more of an app issue but it's somewhat related to #106.

**Comment by ovalseven8** [comment]
Using congstar - but not sure if that has something to do with this issue.
