### ISSUE TITLE
Threema app crashes when stopping session

### ISSUE THREAD

**Issue by ovalseven8** [threema-ch/threema-web#326]
## Steps to Reproduce (for bugs)
1. Go to the "Threema Web" menu in the app
2. Start session manually in the app (but do not try to reconnect in the browser!)
3. Stop session manually in the app
4. App crashes

```
Thu Sep 07 22:02:32 GMT+02:00 2017	connection already active
Thu Sep 07 22:02:32 GMT+02:00 2017	ThreemaConnection state changed: LOGGEDIN Port: 5222 IPv6: false
Thu Sep 07 22:03:04 GMT+02:00 2017	releaseConnectionLinger: source = activityPaused, timeout = 60000
Thu Sep 07 22:03:04 GMT+02:00 2017	Cancel Alarm 1
Thu Sep 07 22:03:04 GMT+02:00 2017	Schedule alarm 1 in 59997ms
Thu Sep 07 22:03:04 GMT+02:00 2017	releaseConnection: source = activityPaused, refCount = 0
Thu Sep 07 22:03:04 GMT+02:00 2017	cleanupConnection: connection must linger for another 59995 milliseconds
Thu Sep 07 22:03:04 GMT+02:00 2017	acquireConnection: source = activityResumed, refCount = 1
Thu Sep 07 22:03:04 GMT+02:00 2017	connection already active
Thu Sep 07 22:03:04 GMT+02:00 2017	releaseConnectionLinger: source = activityPaused, timeout = 60000
Thu Sep 07 22:03:04 GMT+02:00 2017	Cancel Alarm 1
Thu Sep 07 22:03:04 GMT+02:00 2017	Schedule alarm 1 in 59997ms
Thu Sep 07 22:03:04 GMT+02:00 2017	releaseConnection: source = activityPaused, refCount = 0
Thu Sep 07 22:03:04 GMT+02:00 2017	cleanupConnection: connection must linger for another 59995 milliseconds
Thu Sep 07 22:03:04 GMT+02:00 2017	acquireConnection: source = activityResumed, refCount = 1
Thu Sep 07 22:03:04 GMT+02:00 2017	connection already active
Thu Sep 07 22:03:05 GMT+02:00 2017	SessionInstanceService[0]: Resuming Threema Web session
Thu Sep 07 22:03:08 GMT+02:00 2017	ach$a: Error: Called setDisconnecting in state CONNECTING
	at ach.a(SourceFile:51)
	at aco.a(SourceFile:90)
	at aaw.a(SourceFile:552)
	at ch.threema.app.webclient.activities.SessionsActivity.a(SourceFile:3503)
	at ch.threema.app.dialogs.SelectorDialog$1.onClick(SourceFile:126)
	at android.support.v7.app.AlertController$AlertParams$3.onItemClick(SourceFile:1046)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1145)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3049)
	at android.widget.AbsListView$3.run(AbsListView.java:3886)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```

## Your Environment
* Threema Web version: 1.5.0
* Threema for Android version: 3.19.2000369

**Comment by dbrgn** [comment]
Thanks for the report. This is already fixed in the current development version (but the new code was not yet tested enough to release it yesterday).

**Comment by ovalseven8** [comment]
Fixed!
